// <auto-generated />
namespace ClubChallenge.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class reversehashsets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reversehashsets));
        
        string IMigrationMetadata.Id
        {
            get { return "202004142345158_reversehashsets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
